### ISSUE TITLE
Polish the type definitions generator

### ISSUE THREAD

**Issue by kainino0x** [gpuweb/types#99]
A while back I wrote this document describing a potential project to fix a few bugs in the generator for WebGPU's TypeScript type definitions to make it more maintainable. I filed these as separate issues on [bikeshed-to-ts](https://github.com/darionco/bikeshed-to-ts), so this is essentially a tracking issue for those - see issues for details, see doc for summary.

https://docs.google.com/document/d/1MVPbUakXBKwvAd5CN3BJd2Ems5OhYhFt5pKpvrw8SN4/edit?usp=sharing&resourcekey=0-wdToK40p4UEnBKMNguYNmw

- [ ] darionco/bikeshed-to-ts#6
- [ ] darionco/bikeshed-to-ts#8
- [ ] darionco/bikeshed-to-ts#9
- [ ] darionco/bikeshed-to-ts#10
- [ ] darionco/bikeshed-to-ts#11
- [ ] darionco/bikeshed-to-ts#12
